### ISSUE TITLE
o psacy ja ta na versao 3, ainda funciona melhor?

### ISSUE THREAD

**Issue by CrashAngelArts** [ricardojosehlima/lemma_spacy_pt#1]
olá, o psacy ja ta na versao 3, este python ainda tem regras que funciona melhor?

**Comment by ricardojosehlima** [comment]
Oi, eu já estava programando fazer o upload da versão para o 3.0 do spacy, mas já coloquei lá - deixei a versão para o spacy 2.x caso alguém ainda esteja usando essa.
O 3.0 mantém o mesmo esquema de olhar para uma lista, que é a mesma da versão 2.x, ou seja, o desempenho do lematizador do spacy para pt-br continua o mesmo, cometendo os erros que estão exemplificados no README - daí ainda a necessidade de um programa para melhorar esse desempenho.

**Comment by CrashAngelArts** [comment]
Olá professor, valeu, gratidão pela atualização...
eu teste a frase: Comemoram-se festas de finais de ano
e festas apareceu como verbo... 
Eu estou tentando desenvolver produto que irá precisar de um analisador de sintaxe muito bem apurado... você sabe se existe algum outro framework que já foram bem resolvidas estas análises de lematização? pra mim poderia ser em qualquer linguagem que eu dou um jeito de portar....

**Comment by ricardojosehlima** [comment]
Oi eu testei o programa aqui (estou usando Spacy 3.1.1 mas acredito que não deve ter diferença para o 3.0) e o resultado foi:
Comemoram-se/Comemoram-se/VERB/Acc/Fem/Ind/Sing/3/Prs/Past/Fin festas/festa/NOUN/Fem/Plur de/de/ADP/ finais/finar/NOUN/Masc/Plur de/de/ADP/ ano/ano/NOUN/Masc/Sing ././PUNCT/ 
comemoram-comemorar se festa de final de ano . 
--> festa já está como substantivo
Ainda assim, respondendo suas pergunta: você pode testar o Stanza (https://stanfordnlp.github.io/stanza/) ou o UdPipe (https://lindat.mff.cuni.cz/services/udpipe/), os dois usam uma lematização melhor do que o Spacy e os dois também fazem uma análise sintaxe bem razoável - vai depender do tipo de uso que você vai querer. O corpus que eles usam é de notícias de jornal, então o quanto mais perto estiver a frase que você vai testar desse tipo de corpus, mais esse analisador tende a acertar. Por conta de querer dar conta de outros tipos de frase, vou nesses meses por vir, mexer no analisador sintático do Spacy para tentar fazer análises sintáticas desses tipos de frase.
